language: ruby
rvm:
  # EL5 & 6
  - 1.8.7
  # EL7
  - 2.0.0
  # Teh f00t00r
  #- ruby-head
script:
  - cat .gemfile.lock
  - bundle exec rake spec
env:
  global:
    - SPEC_OPTS="-fd"
  matrix:
    - PUPPET_VERSION="~> 2.7.0"
    - PUPPET_VERSION="~> 3"
gemfile: .gemfile
matrix:
    fast_finish: true
    allow_failures:
        - rvm: 2.0.0
        - rvm: ruby-head
    exclude:
        - rvm: 2.0.0
          env: PUPPET_VERSION="~> 2.7.0"
        - rvm: ruby-head
          env: PUPPET_VERSION="~> 2.7.0"
notifications:
  email: false
